/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/3dmodel/benifit.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/benifit.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.002']} position={[1.331, 0, 0.224]} scale={[5.381, 1, 5.015]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.001']} position={[1.331, 1.01, -1.859]} scale={[2.042, 1, 0.145]} />
      <mesh geometry={nodes.fff.geometry} material={materials['Material.003']} position={[0.762, 0.307, -1.622]} rotation={[1.542, 0, 0]} scale={[1, 1.507, 0.971]} />
      <mesh geometry={nodes.fff001.geometry} material={materials['Material.003']} position={[-0.699, 1.159, -1.613]} rotation={[1.542, 0, 0]} scale={[1, 1.507, 0.971]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.Material} position={[0.042, 0.101, 0]}>
        <mesh geometry={nodes.Circle.geometry} material={materials.Material} position={[0, 0.174, -0.007]} />
        <mesh geometry={nodes.Cone001.geometry} material={materials['Material.005']} position={[0.216, 0.173, -0.2]} />
        <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[0, 0.289, -0.011]} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.Material} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/benifit.glb')
