/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/3dmodel/Chair.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Chair.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.002']} position={[2.295, 5.987, -5.557]} rotation={[2.037, 0.326, 0.524]} scale={1.584} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.FabricDenim003_3K} position={[0.04, 2.271, 0.04]} scale={[0.608, 0.12, 0.608]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.WoodQuarteredChiffon001_6K} position={[0.042, 1.328, 0.035]} rotation={[-0.003, 0.8, 0.248]} scale={[0.076, 0.786, 0.077]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.FabricDenim003_3K} position={[0.04, 2.933, 0.001]} scale={0.874} />
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[0, 0.057, 0]} scale={108} />
    </group>
  )
}

useGLTF.preload('/Chair.glb')
