/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/3dmodel/fancy.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/fancy.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube002.geometry} material={materials.Material} position={[0.042, 0.101, 0]}>
        <mesh geometry={nodes.Circle.geometry} material={materials.Material} position={[0, 0.174, -0.007]} />
        <mesh geometry={nodes.Cone001.geometry} material={materials['Material.005']} position={[0.216, 0.173, -0.2]} />
        <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[0, 0.289, -0.011]} />
        <mesh geometry={nodes.Cube001.geometry} material={materials.Material} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/fancy.glb')
