/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/3dmodel/hydria_apothecary_vase.glb 
Author: Virtual Museums of Małopolska (https://sketchfab.com/WirtualneMuzeaMalopolski)
License: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
Source: https://sketchfab.com/3d-models/hydria-apothecary-vase-7d6938c0c0b54b06a0210a982a73023e
Title: Hydria apothecary vase
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hydria_apothecary_vase.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-162.834, -138.288, -228.746]}>
          <mesh geometry={nodes.Object_3.geometry} material={materials.wire_177028149} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.wire_177028149} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.wire_177028149} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.wire_177028149} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.wire_177028149} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.wire_177028149} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.wire_177028149} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/hydria_apothecary_vase.glb')
