/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/3dmodel/Modern.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Modern.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube003.geometry} material={materials.FabricDenim003_3K} position={[0.04, 2.271, 0.04]} scale={[0.608, 0.12, 0.608]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.WoodQuarteredChiffon001_6K} position={[0.042, 1.328, 0.035]} rotation={[-0.003, 0.8, 0.248]} scale={[0.076, 0.786, 0.077]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.FabricDenim003_3K} position={[0.04, 2.933, 0.001]} scale={0.874} />
    </group>
  )
}

useGLTF.preload('/Modern.glb')
