/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/3dmodel/untitled.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/untitled.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.083, 2.655, 1.447]} rotation={[-Math.PI / 2, 0, 0]} scale={0.022}>
        <group position={[-162.834, -138.288, -228.746]}>
          <mesh geometry={nodes.Object_3.geometry} material={materials.wire_177028149} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.wire_177028149} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.wire_177028149} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.wire_177028149} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.wire_177028149} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.wire_177028149} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.wire_177028149} />
        </group>
      </group>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[-0.083, 2.655, 1.447]} scale={0.022} />
    </group>
  )
}

useGLTF.preload('/untitled.glb')
